FROM astrocrpublic.azurecr.io/runtime:3.1-14

COPY include/merged_df.csv /usr/local/airflow/include/
COPY include/model_anomaly.pkl /usr/local/airflow/include/
COPY include/model_soh.pkl /usr/local/airflow/include/
COPY include/model_rul.pkl /usr/local/airflow/include/